backend:
  name: github
  repo: spattk/hugo-xmin-test
  branch: main
  site_domain: superlative-taffy-795952.netlify.app

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "post"
    label: "Posts"
    folder: "content/post"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    folder: "content"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }